import type { SentinelReport } from "../types.js";
import { renderAttackGraph } from "./attackGraph.js";

const SEVERITY_EMOJI: Record<string, string> = {
  critical: "🔴",
  high: "🟠",
  medium: "🟡",
  low: "🔵",
  info: "⚪",
};

export function buildMarkdownReport(report: SentinelReport): string {
  const verifiedChains = report.chains.filter((c) => c.verification.verified);
  const unverifiedChains = report.chains.filter((c) => !c.verification.verified);

  const lines: string[] = [];
  lines.push(`# SentinelAI Report — ${report.repo.owner}/${report.repo.name}`);
  lines.push("");
  lines.push(`Generated ${report.generatedAt} • ${report.findings.length} raw findings → ${report.chains.length} candidate attack chain(s) → **${verifiedChains.length} verified**`);
  lines.push("");

  if (verifiedChains.length > 0) {
    lines.push("## Verified attack stories");
    lines.push("");
    for (const vc of verifiedChains) {
      lines.push(...renderChainSection(vc, true));
    }
  } else {
    lines.push("## Verified attack stories");
    lines.push("");
    lines.push("_None of the candidate chains could be dynamically or statically confirmed this run._");
    lines.push("");
  }

  if (unverifiedChains.length > 0) {
    lines.push("## Candidate chains (not confirmed)");
    lines.push("");
    for (const vc of unverifiedChains) {
      lines.push(...renderChainSection(vc, false));
    }
  }

  lines.push("## Raw findings (Sense stage)");
  lines.push("");
  lines.push("| Severity | Tool | File | Rule | Message |");
  lines.push("|---|---|---|---|---|");
  for (const f of report.findings) {
    lines.push(
      `| ${SEVERITY_EMOJI[f.severity] ?? ""} ${f.severity} | ${f.tool} | \`${f.file}${f.line ? ":" + f.line : ""}\` | ${f.ruleId} | ${f.message.replace(/\|/g, "\\|")} |`
    );
  }
  lines.push("");
  lines.push("---");
  lines.push("_Generated by SentinelAI — reasoning layer on top of Semgrep, Gitleaks, and OSV-Scanner._");

  return lines.join("\n");
}

function renderChainSection(
  vc: SentinelReport["chains"][number],
  verified: boolean
): string[] {
  const { chain, verification } = vc;
  const lines: string[] = [];
  lines.push(`### ${verified ? "✅" : "❔"} ${chain.title}`);
  lines.push("");
  lines.push(`**Impact:** ${chain.impact}`);
  lines.push("");
  lines.push(chain.narrative);
  lines.push("");
  lines.push("```mermaid");
  lines.push(renderAttackGraph(vc));
  lines.push("```");
  lines.push("");
  lines.push(`**Verification (${verification.method}):** ${verification.summary}`);
  lines.push("");
  lines.push(`**Suggested fix:** ${chain.suggestedFix.summary}`);
  if (chain.suggestedFix.diffHint) {
    lines.push("");
    lines.push("```");
    lines.push(chain.suggestedFix.diffHint);
    lines.push("```");
  }
  lines.push("");
  return lines;
}
